### ISSUE TITLE
Display blinks on launch

### ISSUE THREAD

**Issue by eightbit0675** [mills32/Adplug-for-8088-86#1]
Hello! The program works great on my Tandy 1000, however my monitor cannot sync to it! It seems it is running at 67Hz for some reason?

**Comment by eightbit0675** [comment]
I tested the first release and v1.1 and they both display fine with no blinking. So, something broke the display in v1.2. Figured I would let you know. I'd love to try the latest release with the Tandy DAC, if I could see it that is! Thanks regardless for bring this out!

**Comment by mills32** [comment]
Thanks, I don't know what changed, I noticed the image was weird in tandy mode (on FPGA core and HDMI, I have no real tandy to test).
EDIT: Oh I changed the screen mode to 40x25 characters, It is a weird mode not used very often, I'll try to fix it

**Comment by mills32** [comment]
Try the exe on the main folder, I think it should work well now on tandy: 
[ADPLAY88_exe.zip](https://github.com/user-attachments/files/17268723/ADPLAY88_exe.zip)

**Comment by eightbit0675** [comment]
It works PERFECTLY now! Thank you! I love this player. It really looks better than ever now as well. Thank you!!
